const UsersData = [
  {
    id: 1,
    name: "Bum Trum",
    email: "bum@gmail.com",
    phone: "1047958802",
    program: "Software Engineering",
    message: "Hello",
  },
  {
    id: 2,
    name: "My Mo",
    email: "my@gmail.com",
    phone: "368880938",
    program: "Information System",
    message: "Hello",
  },
  {
    id: 3,
    name: "Joe Nguyen",
    email: "joe@gmail.com",
    phone: "103346696",
    program: "Information Assurance",
    message: "Hello",
  },
  {
    id: 4,
    name: "Kevin Khang",
    email: "khang@gmail.com",
    phone: "576510466",
    program: "Internet of Things",
    message: "Hello",
  },
  {
    id: 5,
    name: "Kane Le",
    email: "kane@gmail.com",
    phone: "359856342",
    program: "Artificial Intelligence",
    message: "Hello",
  },
  {
    id: 6,
    name: "Bin Pham",
    email: "bin@gmail.com",
    phone: "475457189",
    program: "Digital Art & Design",
    message: "Hello",
  },
];
export default UsersData;
